local Constants = {
	TEST_MAP_ENABLED = true,
	STRICT_MAP_VALIDATION = false,
	DEBUG_COMMANDS_ENABLED = false,
	RUNTIME_AUDIT_ENABLED = true,
	RUNTIME_AUDIT_INTERVAL = 5,
	FALL_RESET_Y = -100,
	MIN_PLAYERS_TO_START = 2,
	LOBBY_COUNTDOWN_SECONDS = 15,
	INTERMISSION_SECONDS = 10,
	RESULTS_DISPLAY_SECONDS = 8,
	ROUND_MIN_PLAYERS = 2, -- Legacy alias. Prefer MIN_PLAYERS_TO_START.
	ROUND_DURATION_SECONDS = 8 * 60,

	DEFAULT_WALK_SPEED = 16,
	THIEF_CROUCH_SPEED = 8,

	THIEF_EXTRACT_HOLD_SECONDS = 5,
	THIEF_EXTRACT_MOVE_CANCEL_DISTANCE = 1,
	OBJECTIVE_INTERACT_DISTANCE = 12,
	OBJECTIVE_SOLO_SECONDS = 18,
	EXTRACT_HOLD_DISTANCE = 10,
	IDOL_INTERACT_DISTANCE = 10,
	EXTRACT_INTERACT_DISTANCE = 14,
	CAGE_RESCUE_DISTANCE = 12,
	CAGE_RESCUE_SECONDS = 4,
	IDOL_CARRIER_SPEED_MULTIPLIER = 0.75,
	IDOL_CARRIER_REVEAL_INTERVAL = 1.25,
	IDOL_CARRIER_REVEAL_DURATION = 1.5,
	GUARDIAN_RUSH_DURATION = 2,
	GUARDIAN_RUSH_COOLDOWN = 10,
	GUARDIAN_RUSH_SPEED_MULTIPLIER = 1.45,
	GUARDIAN_REVEAL_DURATION = 4,
	GUARDIAN_REVEAL_COOLDOWN = 30,
	GUARDIAN_ROAR_RADIUS = 22,
	GUARDIAN_ROAR_SLOW_DURATION = 2.5,
	GUARDIAN_ROAR_SLOW_MULTIPLIER = 0.55,
	GUARDIAN_ROAR_COOLDOWN = 18,

	GUARDIAN_CATCH_DISTANCE = 5,

	THIEF_FOOTSTEP_VOLUME_SCALE_CROUCH = 0.25,

	GUARDIAN_SPAWN_POSITION = Vector3.new(0, 1, 0),
	CAGE_SPAWN_POSITION = Vector3.new(-70, 2, 60),
	THIEF_SPAWN_POSITIONS = {
		Vector3.new(-20, 1, -60),
		Vector3.new(-7, 1, -60),
		Vector3.new(7, 1, -60),
		Vector3.new(20, 1, -60),
	},
	-- Test map spawn positions (override for test map layout)
	TEST_THIEF_SPAWN_POSITIONS = {
		Vector3.new(-24, 1.5, -75),
		Vector3.new(-8, 1.5, -75),
		Vector3.new(8, 1.5, -75),
		Vector3.new(24, 1.5, -75),
	},
	TEST_GUARDIAN_SPAWN_POSITION = Vector3.new(0, 1.5, 18),

	BRAZIER_INTERACT_DISTANCE = 8, -- Legacy map compatibility only.
	BRAZIER_SEQUENCE_LENGTH = 4, -- Legacy map compatibility only.
}

return Constants
