local Constants = {
	ROUND_MIN_PLAYERS = 1,
	ROUND_DURATION_SECONDS = 8 * 60,

	DEFAULT_WALK_SPEED = 16,
	THIEF_CROUCH_SPEED = 8,
	GUARDIAN_SPRINT_SPEED = 24,
	GUARDIAN_SPRINT_DURATION_SECONDS = 6,
	GUARDIAN_SPRINT_COOLDOWN_SECONDS = 10,

	THIEF_EXTRACT_DISTANCE = 10,
	THIEF_EXTRACT_HOLD_SECONDS = 5,
	THIEF_EXTRACT_MOVE_CANCEL_DISTANCE = 1,

	GUARDIAN_CATCH_DISTANCE = 5,

	THIEF_FOOTSTEP_VOLUME_SCALE_CROUCH = 0.25,
}

return Constants
